# Generated by Django 3.0 on 2020-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
